# Builds the sleeve badges of the bōsōzoku shirt: seal stamp on top, rank in brush kanji, English rank below.
#   python merch/bosozoku/build-sleeve.py   (or run export.sh for everything)
# Writes out/sleeve-zako.svg and out/sleeve-bancho.svg: pure vector (Spreadshop prints
# sleeves from vectors only), 7.5 x 7.5 cm, two colours (red + white), all text outlined, seal inlined.
import re
import os
os.chdir(os.path.dirname(os.path.abspath(__file__)))   # paths below are relative to merch/bosozoku/
from fontTools.ttLib import TTFont
from fontTools.pens.svgPathPen import SVGPathPen

RANKS = {"zako": ("雑魚", "GOON"), "bancho": ("番長", "RINGLEADER")}
RED, WHITE = "#d4000c", "#f2f2f2"
S = 300                                    # canvas units, 300 = 7.5 cm

def outline(text, font_file, x_centre, baseline, size, fill, max_width=None, spacing=0):
    f = TTFont(font_file)
    cmap, glyphs, hmtx, upm = f.getBestCmap(), f.getGlyphSet(), f["hmtx"], f["head"].unitsPerEm
    names = [cmap[ord(c)] for c in text]
    k = size / upm
    width = sum(hmtx[n][0] * k + spacing for n in names) - spacing
    if max_width and width > max_width:
        shrink = max_width / width
        k, spacing, width = k * shrink, spacing * shrink, max_width
    x, out = x_centre - width / 2, []
    for n in names:
        pen = SVGPathPen(glyphs)
        glyphs[n].draw(pen)
        out.append('<path transform="translate(%.2f %.2f) scale(%.5f %.5f)" d="%s"/>' % (x, baseline, k, -k, pen.getCommands()))
        x += hmtx[n][0] * k + spacing
    return '<g fill="%s">%s</g>' % (fill, "".join(out))

def inline_svg(path, x, y, w, h):
    svg = open(path, encoding="utf-8").read()
    svg = re.sub(r"<\?xml[^>]*>|<!--.*?-->", "", svg, flags=re.S)
    return re.sub(r"<svg\b[^>]*?>", lambda m: re.sub(r'\s(width|height|x|y)="[^"]*"', "", m.group(0))
                  .replace("<svg", '<svg x="%g" y="%g" width="%g" height="%g"' % (x, y, w, h), 1), svg, count=1)

for key, (kanji, english) in RANKS.items():
    body = [
        inline_svg("../shared/stamps/stamp-seal.svg", 70, 0, 160, 160),                                   # seal, 4 cm
        outline(kanji, "../shared/fonts/YujiBoku-Regular.ttf", S / 2, 246, 82, WHITE, spacing=6),  # rank kanji
        outline(english, "C:/Windows/Fonts/impact.ttf", S / 2, 294, 38, RED, max_width=220, spacing=3),
    ]
    out = f'''<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by build-sleeve.py. Sleeve badge ({english}), 7.5 x 7.5 cm, vector only. -->
<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink"
     width="75mm" height="75mm" viewBox="0 0 {S} {S}">
{chr(10).join(body)}
</svg>
'''
    open(f"out/sleeve-{key}.svg", "w", encoding="utf-8").write(out)
    print("wrote", f"out/sleeve-{key}.svg")
