# Builds out/back.svg: tokkō-fuku style back print with vertical "embroidered" kanji columns.
#   python merch/bosozoku/build-back.py [side font]   (or run export.sh for everything)
# Kanji are outlined from a brush font (no install needed), white with a red border like embroidery.
# Columns read right to left: slogan, team name (big, centre), slogan. Logo silhouette sits behind.
import re
import os
os.chdir(os.path.dirname(os.path.abspath(__file__)))   # paths below are relative to merch/bosozoku/
from fontTools.ttLib import TTFont
from fontTools.pens.svgPathPen import SVGPathPen

FONT = "../shared/fonts/YujiBoku-Regular.ttf"
import sys
SIDE_FONT = sys.argv[1] if len(sys.argv) > 1 else "C:/Windows/Fonts/OLDENGL.TTF"  # English sides: blackletter, like bōsōzoku coats
W, H = 1200, 1600
WHITE, RED = "#f2f2f2", "#d4000c"
LOGO_BASE, LOGO_DETAIL = "#2c0305", "#55060c"  # logo in two dark reds: still readable, stays in the background

COLUMNS = [  # kanji, top to bottom: text, centre x, top y, character size, fill, border width
    ("魔奴義亜", 600, 110, 330, WHITE, 24),
]
SIDES = [  # English, rotated 90 degrees (reads top to bottom, like a book spine):
           # parts [(text, letter spacing)], centre x, centre y, size, gap between parts
    ([("MadGear", 4), ("FFM", -14)], 1035, 820, 150, 34),
    ([("Frankfurt am Main", 2)], 165, 820, 120, 0),
]

font = TTFont(FONT)
cmap, glyphs, hmtx = font.getBestCmap(), font.getGlyphSet(), font["hmtx"]
upm = font["head"].unitsPerEm
ascent = font["hhea"].ascent

def column(text, cx, top, size, fill, border):
    s = size / upm
    out = []
    for i, ch in enumerate(text):
        name = cmap[ord(ch)]
        pen = SVGPathPen(glyphs)
        glyphs[name].draw(pen)
        x = cx - hmtx[name][0] * s / 2
        y = top + i * size * 1.03 + ascent * s
        out.append('<path transform="translate(%.1f %.1f) scale(%.5f %.5f)" d="%s"/>' % (x, y, s, -s, pen.getCommands()))
    style = 'fill="%s"' % fill
    if border:  # border drawn under the fill = embroidered outline
        style += ' stroke="%s" stroke-width="%.1f" stroke-linejoin="round" paint-order="stroke"' % (RED, border / s)
    return '<g %s>%s</g>' % (style, "".join(out))

sfont = TTFont(SIDE_FONT)
scmap, sglyphs, shmtx = sfont.getBestCmap(), sfont.getGlyphSet(), sfont["hmtx"]
supm = sfont["head"].unitsPerEm

def side(parts, cx, cy, size, gap):
    s = size / supm
    glyph_runs = []  # (glyph name, advance) for every letter, gap added after each part
    for k, (text, spacing) in enumerate(parts):
        names = [scmap[ord(c)] for c in text]
        run = [(n, shmtx[n][0] * s + spacing) for n in names]
        run[-1] = (run[-1][0], run[-1][1] - spacing + (gap if k < len(parts) - 1 else 0))
        glyph_runs += run
    x = -sum(a for _, a in glyph_runs) / 2
    out = []
    for n, adv in glyph_runs:
        pen = SVGPathPen(sglyphs)
        sglyphs[n].draw(pen)
        out.append('<path transform="translate(%.1f %.1f) scale(%.5f %.5f)" d="%s"/>' % (x, size * 0.35, s, -s, pen.getCommands()))
        x += adv
    return '<g fill="%s" transform="translate(%.1f %.1f) rotate(90)">%s</g>' % (RED, cx, cy, "".join(out))

# Logo as a dark "silhouette": white base and red details become two dark reds.
logo = open("../../public/logo-mark.svg", encoding="utf-8").read()
logo = logo.replace("fill:#ffffff", "fill:" + LOGO_BASE).replace("fill:#c8000a", "fill:" + LOGO_DETAIL)
logo = re.sub(r"<\?xml[^>]*>", "", logo)
logo = re.sub(r"<svg\b[^>]*?>", lambda m: re.sub(r'\s(width|height)="[^"]*"', "", m.group(0))
              .replace("<svg", '<svg x="100" y="300" width="1000" height="1012"', 1), logo, count=1)

svg = f'''<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by build-back.py, edit that instead. Back print, dark shirt, 30 x 40 cm. -->
<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink"
     width="300mm" height="400mm" viewBox="0 0 {W} {H}">
{logo}
{"".join(column(*c) for c in COLUMNS)}
{"".join(side(*c) for c in SIDES)}
</svg>
'''
open("out/back.svg", "w", encoding="utf-8").write(svg)
print("wrote out/back.svg")
