# Builds shirt-bosozoku-front.svg: fake tokkō-fuku coat front (trompe-l'œil) for the bōsōzoku shirt.
#   python build-bosozoku-front.py
# Double-breasted button rows with a stitched placket, a stitched chest pocket with the logo stamp as patch,
# and plain readable text (Impact) on the pocket flap.
from fontTools.ttLib import TTFont
from fontTools.pens.svgPathPen import SVGPathPen

W, H = 1200, 1600
THREAD, BUTTON, RED = "#cfcfd6", "#bfbfc6", "#d4000c"
STITCH = 'fill="none" stroke="%s" stroke-width="5" stroke-dasharray="16 10" stroke-linecap="round"' % THREAD

ROWS_X = (505, 695)                       # button rows, either side of the centre
BUTTONS_Y = (330, 560, 790, 1020, 1250)   # button heights
POCKET = (150, 420, 260, 300)             # x, y, width, height (viewer's left, away from the panel edge)
FLAP_H = 80
FLAP_TEXT = "MADGEARFFM"

def button(cx, cy, r=34):
    # metal button: ring + four thread holes cut out
    holes = "".join('<circle cx="%.1f" cy="%.1f" r="5.5" fill="#000"/>' % (cx + dx, cy + dy)
                    for dx, dy in ((-9, -9), (9, -9), (-9, 9), (9, 9)))
    return ('<mask id="b%d_%d" maskUnits="userSpaceOnUse" x="0" y="0" width="%d" height="%d">'
            '<circle cx="%.1f" cy="%.1f" r="%d" fill="#fff"/><circle cx="%.1f" cy="%.1f" r="%d" fill="none" stroke="#000" stroke-width="4"/>%s</mask>'
            '<circle cx="%.1f" cy="%.1f" r="%d" fill="%s" mask="url(#b%d_%d)"/>'
            % (cx, cy, W, H, cx, cy, r, cx, cy, r - 9, holes, cx, cy, r, BUTTON, cx, cy))

def text(s, x_centre, baseline, size, fill, max_width=None, font="C:/Windows/Fonts/impact.ttf", spacing=3):
    f = TTFont(font)
    cmap, glyphs, hmtx, upm = f.getBestCmap(), f.getGlyphSet(), f["hmtx"], f["head"].unitsPerEm
    names = [cmap[ord(c)] for c in s]
    k = size / upm
    width = sum(hmtx[n][0] * k + spacing for n in names) - spacing
    if max_width and width > max_width:  # shrink to fit
        k *= max_width / width
        width = max_width
    x, out = x_centre - width / 2, []
    for n in names:
        pen = SVGPathPen(glyphs)
        glyphs[n].draw(pen)
        out.append('<path transform="translate(%.1f %.1f) scale(%.5f %.5f)" d="%s"/>' % (x, baseline, k, -k, pen.getCommands()))
        x += hmtx[n][0] * k + spacing
    return '<g fill="%s">%s</g>' % (fill, "".join(out))

parts = []
# placket: edge of the overlapping front panel of a double-breasted coat, shown only as stitching
parts.append('<path d="M 790 150 L 790 1560" %s/>' % STITCH)
# buttons
for y in BUTTONS_Y:
    for x in ROWS_X:
        parts.append(button(x, y))
# pocket: stitched outline, flap with text, logo stamp as patch
px, py, pw, ph = POCKET
parts.append('<rect x="%d" y="%d" width="%d" height="%d" rx="10" %s/>' % (px, py, pw, ph, STITCH))
parts.append('<path d="M %d %d L %d %d" %s/>' % (px, py + FLAP_H, px + pw, py + FLAP_H, STITCH))
parts.append(text(FLAP_TEXT, px + pw / 2, py + FLAP_H - 22, 46, "#f2f2f2", max_width=pw - 40))
parts.append('<image href="stamp-logo.svg" x="%.1f" y="%.1f" width="170" height="170" />' % (px + (pw - 170) / 2, py + FLAP_H + 25))

svg = f'''<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by build-bosozoku-front.py, edit that instead. Front print, dark shirt, 30 x 40 cm. -->
<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink"
     width="300mm" height="400mm" viewBox="0 0 {W} {H}">
{chr(10).join(parts)}
</svg>
'''
open("shirt-bosozoku-front.svg", "w", encoding="utf-8").write(svg)
print("wrote shirt-bosozoku-front.svg")
